### ISSUE TITLE
New rule

### ISSUE THREAD

**Issue by akinci23** [DoctorAnon/TheRightCafe#1]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] Yes, I fear the longevity of the server will be lowered.

**Describe the solution you'd like** 
A rule which prohibits the use of slurs and/or expression of anything which could threaten the server's reputation & longevity (before it gets banned ofc)
**Why is this solution necessary?** It should keep us further away from the ban hammer of gay discord 

**Additional context**

**Comment by DoctorAnon** [comment]
Would you rather a completely new rule be added or replace already-existing rule?
